#!/bin/sh
set -eu
if [ "${SSH_ORIGINAL_COMMAND:-}" != "restart-remnanode" ]; then
  logger -t monitor-heal "rejected SSH command from ${USER:-unknown}"
  exit 64
fi
exec /usr/bin/sudo -n /usr/local/sbin/monitor-heal-action
